"""Описание изменений

Revision ID: ecee56f6c39b
Revises: 
Create Date: 2025-04-04 18:07:22.025592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecee56f6c39b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('passphrase', sa.String(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_accessed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_id'), 'secrets', ['id'], unique=False)
    op.create_index(op.f('ix_secrets_secret_key'), 'secrets', ['secret_key'], unique=True)
    op.create_table('secret_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_id', sa.Integer(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_logs_id'), 'secret_logs', ['id'], unique=False)
    op.create_index(op.f('ix_secret_logs_secret_key'), 'secret_logs', ['secret_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_logs_secret_key'), table_name='secret_logs')
    op.drop_index(op.f('ix_secret_logs_id'), table_name='secret_logs')
    op.drop_table('secret_logs')
    op.drop_index(op.f('ix_secrets_secret_key'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_id'), table_name='secrets')
    op.drop_table('secrets')
    # ### end Alembic commands ###
